# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [3]:
b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


4. Find the shape of previous array in question 3

In [4]:
print(b.shape)

(40,)


5. Print the type of the previous array in question 3

In [5]:
print(type(b))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [6]:
print(np.__version__)

1.19.2


7. Print the dimension of the array in question 3


In [7]:
print(b.ndim)

1


8. Create a boolean array with all the True values

In [8]:
c = np.full((2,2),True)
print(c)

[[ True  True]
 [ True  True]]


9. Create a two dimensional array




In [9]:
d = np.arange(9).reshape(3,3)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Create a three dimensional array



In [10]:
e = np.arange(27).reshape(3,3,3)
print(e)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
f = np.arange(5)
print(f[::-1])

[4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
g= np.zeros(10)
g[5]=1
print(g)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


13. Create a 3x3 identity matrix

In [13]:
h = np.arange(9).reshape(3,3)
print(h)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
i = np.array([1,2,3,4,5],dtype="float64")
print(i)

[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
print(arr1*arr2)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
j = np.array(arr1==arr2)
print(j)

[[False False False]
 [False False False]]


17. Extract all odd numbers from arr with values(0-9)

In [17]:
k = np.arange(10)
print(k[k%2!=0])

[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [18]:
k[k%2!=0] = -1
print(k)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[5:9] = 12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

In [20]:
l = np.ones(25).reshape(5,5)
l[1:-1,1:-1] = 0
print(l)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1,1] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,0,0:] = 64
print(arr3d)

[[[64 64 64]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
m = np.arange(9).reshape(3,3)
print(m[0,0])

0


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
m1 = np.arange(9).reshape(3,3)
print(m1[1,1])

4


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
m2 = np.arange(9).reshape(3,3)
print(m2[:2,2])

[2 5]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
from numpy import random
n = random.randint(100,size=(10,10))
print(n)
print("The Maximum Value from Above Array is",np.max(n,axis=None))
print("The Minimum Value From Above Array Is",np.min(n))

[[50 83  1 56 70 62 56 98 17 95]
 [93 43 74 97 94 97 29 92 39 19]
 [26 84 91 82 71  9 84 87 81 44]
 [17 13 56 13 48 96 34 29 98 43]
 [79  3 31 54 74 17 81 75 41 23]
 [11 39 17 51 72 91 38  9 19 78]
 [95 26 12  9 86 37 66 51 67 18]
 [53 39  8 77 30 78 53 86  2 28]
 [48 18 24 45 63 65 26 58 68 92]
 [76 97 73 80  8 62 73 73 85 47]]
The Maximum Value from Above Array is 98
The Minimum Value From Above Array Is 1


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
print(np.where(a==b))

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data[names!='Will'])

[[-0.58291391 -0.80963624 -2.36053953 -0.51575428]
 [ 1.95757828  1.42049949  0.68997322  3.14708388]
 [ 0.77445141 -0.11113568  1.42058979  0.81440341]
 [ 1.2344165   1.46962287 -1.33399724  0.03343366]
 [-0.57856768 -0.00694621 -0.69124035 -0.1835352 ]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
mask = (names!='Joe')&(names!='Will')
print(data[mask])

[[ 0.2241098  -0.70494484 -1.87855791 -0.71653496]
 [ 0.42181196  0.50669619 -0.67137288 -1.15801858]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
print(np.random.uniform(low=1,high=15,size=(5,3)))

[[ 7.26933988  6.49556718 10.39327837]
 [ 3.87863773  5.75659449  5.0687509 ]
 [ 5.56104394  1.55769825 10.42274936]
 [13.07007737  2.59657563 13.11454095]
 [ 3.78711375 14.31177158 11.4677917 ]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:
o = np.random.uniform(low=1,high=16,size=(2,2,4))
print(o)

[[[ 5.73363347 15.04942612 14.58396403 10.71613494]
  [ 9.05201909 15.63660815  1.15274584  3.55701482]]

 [[11.71917143  4.54676119 15.63930346 13.98420185]
  [ 3.57478979 13.20927273 13.01543766 11.33583918]]]


33. Swap axes of the array you created in Question 32

In [33]:
print(o.transpose())

[[[ 5.73363347 11.71917143]
  [ 9.05201909  3.57478979]]

 [[15.04942612  4.54676119]
  [15.63660815 13.20927273]]

 [[14.58396403 15.63930346]
  [ 1.15274584 13.01543766]]

 [[10.71613494 13.98420185]
  [ 3.55701482 11.33583918]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
p = np.sqrt(np.random.uniform(low=0.01,high=2,size=10))
print(p)
print(np.where(p<0.5,p*0,p))

[1.30303705 1.06277678 0.98378041 0.65719632 1.04291071 1.04606785
 1.38157336 1.03033998 1.00873001 0.31272719]
[1.30303705 1.06277678 0.98378041 0.65719632 1.04291071 1.04606785
 1.38157336 1.03033998 1.00873001 0.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
p1 = np.random.randint(15,size=12)
p2 = np.random.randint(15,size=12)
result = np.maximum(p1,p2)
print(result)

[ 7  1  4 11  8 12  6  8  5  8  6 12]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
q = np.array(np.unique(names))
print(q)

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [37]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
a=np.setdiff1d(a,b)
print(a)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [38]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
new_array = np.delete(sampleArray,1,1)
newColumn = np.array([[10,10,10]])
final_array = np.insert(new_array,1,newColumn,axis=1)
print(final_array)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [39]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
result=np.dot(x,y)
print(result)

[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [40]:
r = np.random.randint(15,size=20)
s = np.cumsum(r)
print(s)

[ 11  14  25  33  36  50  60  70  83  90 101 106 119 132 144 144 156 160
 169 174]
