In [1]:
import numpy as np

In [4]:
x = np.random.randn(10,10)

In [5]:
x[1:10:2,::]

array([[ 0.38885451, -0.92292594,  0.50882242,  0.47451332,  0.3487742 ,
        -0.38899358, -1.38358143,  0.33569485, -0.54375681,  0.12977038],
       [-0.25815368,  0.01749647, -1.07952579, -0.60045529, -0.22948139,
        -1.18738095, -0.37354556, -1.04534801,  0.8417057 , -1.34845108],
       [ 0.16370756,  1.92872546,  0.18900596, -0.37293972,  0.54395565,
         2.28304702, -1.3916414 , -1.33756361,  1.07887333, -1.19693629],
       [-0.31366396, -1.14714308, -0.52386794, -0.29881006,  1.95555001,
        -0.69087962,  0.74825846,  0.192872  , -1.17737544, -0.38657788],
       [-0.33573302,  0.70297912,  0.57373402,  1.33266791,  0.74461841,
         0.48297587,  0.13134423, -2.72077777, -0.49580321, -1.60411029]])

In [6]:
x[::,0:4]

array([[ 0.40047299, -0.26156808, -0.91398801, -0.95767907],
       [ 0.38885451, -0.92292594,  0.50882242,  0.47451332],
       [-1.98096813, -0.53463222,  3.09812886, -0.77230766],
       [-0.25815368,  0.01749647, -1.07952579, -0.60045529],
       [-0.15842348, -1.52378295, -0.77639339,  0.48994266],
       [ 0.16370756,  1.92872546,  0.18900596, -0.37293972],
       [ 0.91290714, -1.32790127, -0.79428605,  0.72955477],
       [-0.31366396, -1.14714308, -0.52386794, -0.29881006],
       [ 0.81971385,  0.95849181, -0.24939337, -1.13645677],
       [-0.33573302,  0.70297912,  0.57373402,  1.33266791]])

In [8]:
a = np.ones((5,5))

In [9]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
a[1:4,1:4]=0

In [12]:
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
b = np.ones((5,8))
print(b)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
b[1:5:2] = 0

In [16]:
print(b)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
