In [1]:
import numpy as np

In [2]:
x = np.array([10,9,8,6,11])

In [3]:
np.sqrt(x)  #taking square root

array([3.16227766, 3.        , 2.82842712, 2.44948974, 3.31662479])

In [4]:
np.power(x,2)  #taking square

array([100,  81,  64,  36, 121])

In [52]:
x = np.array([10,9,8,6,11])
y = np.array([7,10,2,3,34])

In [53]:
np.maximum(x,y) #compare each member and bring maximum member. NOTE: no. of member should be equal

array([10, 10,  8,  6, 34])

In [14]:
salary = np.array([0,-1,100000,50000])

In [19]:
# syntax-->  np.where(condition,true,false)
np.where(salary<=0,"not okay","okay")

array(['not okay', 'not okay', 'okay', 'okay'], dtype='<U8')

In [21]:
a = np.arange(1,21)

In [22]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
np.where(a%2,"odd","even")

array(['odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even'], dtype='<U4')

In [46]:
x = np.arange(1,21)

In [41]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [45]:
x.reshape(5,2,2)
# 5 part hony chahiye or har part mein 2 part honay chahiye or or us ky har part mein 2 member honay chahiye

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])

In [47]:
#or
x.reshape(5,2,-1)
# -1 tells that we dont't know what value should be placed there. numpy auto placed appropiate value on there

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])

In [43]:
x.reshape((5,2,-1),order='F')

array([[[ 1, 11],
        [ 6, 16]],

       [[ 2, 12],
        [ 7, 17]],

       [[ 3, 13],
        [ 8, 18]],

       [[ 4, 14],
        [ 9, 19]],

       [[ 5, 15],
        [10, 20]]])

In [44]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [54]:
x = np.random.randn(4,2)
print(x)

[[ 0.07200736 -1.44259908]
 [ 1.15302693 -0.8598314 ]
 [ 1.44865032 -0.94943389]
 [-0.84758574 -1.96157626]]


In [55]:
x.ravel()   # convert array into one dimension

array([ 0.07200736, -1.44259908,  1.15302693, -0.8598314 ,  1.44865032,
       -0.94943389, -0.84758574, -1.96157626])

In [56]:
x.flatten() # convert array into one dimension

array([ 0.07200736, -1.44259908,  1.15302693, -0.8598314 ,  1.44865032,
       -0.94943389, -0.84758574, -1.96157626])

### concatenation

In [57]:
arr1 = np.array([[1,3,5],[7,9,0]])
arr2 = np.array([[11,13,15],[17,19,10]])

In [61]:
np.concatenate((arr1,arr2),axis=0)    #row-wise concatenation
#OR
np.vstack((arr1,arr2)) #same result

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [11, 13, 15],
       [17, 19, 10]])

In [65]:
np.concatenate((arr1,arr2),axis=1)   #column wise concatenation
#OR
np.hstack((arr1,arr2))

array([[ 1,  3,  5, 11, 13, 15],
       [ 7,  9,  0, 17, 19, 10]])

### SPLIT

In [66]:
arr3 = np.arange(1,31)
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [67]:
# np.split(arr3,[index_no.+1,index_no.+1,index_no.+1])
np.split(arr3,[5,10,15,20,25])
#              1  2  3  4  5   --> 6 parts

[array([1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20]),
 array([21, 22, 23, 24, 25]),
 array([26, 27, 28, 29, 30])]

### Splitting of two dimension array 

In [69]:
arr4 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(arr4)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [75]:
#               column no.
h = np.split(arr4,[2,5],axis=1 )
print(h)
h = np.hsplit(arr4,[2,5]) # same result
print('-----------------')
print(h)

[array([[1, 2],
       [7, 8]]), array([[ 3,  4,  5],
       [ 9, 10, 11]]), array([[ 6],
       [12]])]
-----------------
[array([[1, 2],
       [7, 8]]), array([[ 3,  4,  5],
       [ 9, 10, 11]]), array([[ 6],
       [12]])]


In [81]:
#               row no.   
h = np.split(arr4,[1],axis=0) 
print(h)
h = np.vsplit(arr4,[1]) # same result
print('----------------------------------------------------------------')
print(h)

[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]
----------------------------------------------------------------
[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]


In [82]:
g = np.array([1,5,7,8])

In [83]:
np.repeat(g,3)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 8, 8, 8])

In [84]:
np.tile(g,2)

array([1, 5, 7, 8, 1, 5, 7, 8])