# Welcome to Jupyter!

In [38]:
import numpy as np

In [8]:
l = range(1000000)
d = np.arange(1000000)
%time for _ in range(10): [i*2 for i in l]
                
        

CPU times: user 770 ms, sys: 247 ms, total: 1.02 s
Wall time: 1.04 s


In [9]:
%time for _ in range (10): d*2

CPU times: user 11.3 ms, sys: 4.88 ms, total: 16.2 ms
Wall time: 15 ms


In [10]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
clr

NameError: name 'clr' is not defined

In [16]:
np.empty((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
list = [1,3,5,6]

In [18]:
np.array(list)

array([1, 3, 5, 6])

In [21]:
a = np.arange(1,100,10)

In [22]:
a

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [23]:
a.shape()

TypeError: 'tuple' object is not callable

In [24]:
a.shape

(10,)

In [29]:
x=np.zeros((10,20))

In [30]:
x.shape

(10, 20)

In [34]:
x=x.reshape(2,4,5,5)

In [35]:
x.dtype

dtype('float64')

In [36]:
x.ndim

4

In [41]:
a = np.random.randn((10))

In [45]:
a = np.arange(1,11,1)
b = np.arange(11,21,1)
print(a,b)

[ 1  2  3  4  5  6  7  8  9 10] [11 12 13 14 15 16 17 18 19 20]


In [46]:
a + b

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [47]:
a-b

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [48]:
b-a

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [49]:
a/b

array([0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333,
       0.375     , 0.41176471, 0.44444444, 0.47368421, 0.5       ])

In [50]:
b/a

array([11.        ,  6.        ,  4.33333333,  3.5       ,  3.        ,
        2.66666667,  2.42857143,  2.25      ,  2.11111111,  2.        ])

In [51]:
a>0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [52]:
a[a<0]

array([], dtype=int64)

In [53]:
a[a>0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
a{0}

SyntaxError: invalid syntax (<ipython-input-54-4435239c6d4a>, line 1)

In [55]:
a[0]

1

In [56]:
a[-1]

10

In [60]:
a[a>5]

array([ 6,  7,  8,  9, 10])